version: '3'

networks:
  cibmtr:
    driver: bridge

volumes:
  mssql-data:
  idp-signing-creds:
  redisdata:
  nlp-solrdata:
  nlp-pgdata:
  nlp-mongodata:
  ingest-files:
  ingest-mongodata:
  certs:
  vhost:
  html:
  dhparam:
  htpasswd:

services:
  mssql:
    container_name: IDP_MSSQL
    hostname: ${IDP_DB_HOSTNAME}
    image: microsoft/mssql-server-linux
    expose:
      - ${IDP_DB_CONTAINER_PORT}
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${IDP_DB_PASSWORD}
      - MSSQL_PID=Developer
    networks:
      - cibmtr

  identity-provider:
    container_name: IDENTITY_PROVIDER
    hostname: identity-provider
    image: claritynlp/identity-provider
    expose:
      - ${IDENTITY_PROVIDER_CONTAINER_PORT}
    volumes:
      - idp-signing-creds:/app/creds
    entrypoint:
      - /app/wait-for-it-extra.sh
      - ${IDP_DB_HOSTNAME}:${IDP_DB_CONTAINER_PORT}
      - --timeout=420
      - --extra=15
      - --
      - docker-entrypoint.sh
    command: dotnet IdentityServer.dll
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - LETSENCRYPT_HOST=${IDENTITY_PROVIDER_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_HOST=${IDENTITY_PROVIDER_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=${IDENTITY_PROVIDER_CONTAINER_PORT}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - SUBDOMAIN=${IDENTITY_PROVIDER_SUBDOMAIN}
      - DASHBOARD_SUBDOMAIN=${DASHBOARD_CLIENT_SUBDOMAIN}
      - INGEST_SUBDOMAIN=${INGEST_CLIENT_SUBDOMAIN}
      - RESULTS_SUBDOMAIN=${RESULTS_CLIENT_SUBDOMAIN}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CLIENT_CLI_SECRET=${CLIENT_CLI_SECRET}
      - CLIENT_NLPASS_SECRET=${CLIENT_NLPASS_SECRET}
      - IDP_DB_PASSWORD=${IDP_DB_PASSWORD}
      - IDP_DATABASE=${IDP_DATABASE}
      - IDP_SIGNING_CREDS_PASSPHRASE=${IDP_SIGNING_CREDS_PASSPHRASE}
    depends_on:
      - mssql
    networks:
      - cibmtr

  identity-and-access-proxy:
    container_name: IDENTITY_AND_ACCESS_PROXY
    hostname: identity-and-access-proxy
    image: claritynlp/identity-and-access-proxy
    expose:
      - ${IDENTITY_AND_ACCESS_PROXY_CONTAINER_PORT}
    entrypoint: pm2-runtime
    command: proxy.js
    environment:
      - LETSENCRYPT_HOST=${IDENTITY_AND_ACCESS_PROXY_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_HOST=${IDENTITY_AND_ACCESS_PROXY_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=${IDENTITY_AND_ACCESS_PROXY_CONTAINER_PORT}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - DASHBOARD_CLIENT_SUBDOMAIN=${DASHBOARD_CLIENT_SUBDOMAIN}
      - INGEST_CLIENT_SUBDOMAIN=${INGEST_CLIENT_SUBDOMAIN}
      - RESULTS_CLIENT_SUBDOMAIN=${RESULTS_CLIENT_SUBDOMAIN}
    networks:
      - cibmtr

  nlp-api:
    container_name: NLP_API
    hostname: ${NLP_API_HOSTNAME}
    image: claritynlp/nlp-api
    expose:
      - ${NLP_API_CONTAINER_PORT}
    entrypoint:
      - /api/wait-for-it-extra.sh
      - ${NLP_SOLR_HOSTNAME}:${NLP_SOLR_CONTAINER_PORT}
      - ${NLP_MONGO_HOSTNAME}:${NLP_MONGO_CONTAINER_PORT}
      - ${SCHEDULER_HOSTNAME}:${SCHEDULER_CONTAINER_PORT}
      - ${NLP_PG_HOSTNAME}:${NLP_PG_CONTAINER_PORT}
      - ${REDIS_HOSTNAME}:${REDIS_CONTAINER_PORT}
      - --timeout=420
      - --
      - python3
    command: api.py
    environment:
      - NLP_API_TMP_DIR=${NLP_API_TMP_DIR}
      - NLP_API_LOG_DIR=${NLP_API_LOG_DIR}
      - NLP_SOLR_URL=${NLP_SOLR_URL}
      - NLP_API_DEBUG_MODE=${NLP_API_DEBUG_MODE}
      - NLP_EXPRESSION_EVALUATOR=${NLP_EXPRESSION_EVALUATOR}
      - NLP_API_URL=${NLP_API_URL}
      - BATCH_SIZE=${BATCH_SIZE}
      - RESULTS_CLIENT_URL=${RESULTS_URL}
      - USE_MEMORY_CACHING=${USE_MEMORY_CACHING}
      - USE_PRECOMPUTED_SEGMENTATION=${USE_PRECOMPUTED_SEGMENTATION}
      - USE_REORDERED_NLPQL=${USE_REORDERED_NLPQL}
      - USE_REDIS_CACHING=${USE_REDIS_CACHING}
      - OHDSI_WEBAPI_URL=${OHDSI_WEBAPI_URL}
      - SOLR_TEXT_FIELD=${SOLR_TEXT_FIELD}
      - SOLR_ID_FIELD=${SOLR_ID_FIELD}
      - SOLR_REPORT_ID_FIELD=${SOLR_REPORT_ID_FIELD}
      - SOLR_SOURCE_FIELD=${SOLR_SOURCE_FIELD}
      - SOLR_REPORT_DATE_FIELD=${SOLR_REPORT_DATE_FIELD}
      - SOLR_SUBJECT_FIELD=${SOLR_SUBJECT_FIELD}
      - SOLR_REPORT_TYPE_FIELD=${SOLR_REPORT_TYPE_FIELD}
      - NLP_PG_HOSTNAME=${NLP_PG_HOSTNAME}
      - NLP_PG_DATABASE=${NLP_PG_DATABASE}
      - NLP_PG_USER=${NLP_PG_USER}
      - NLP_PG_PASSWORD=${NLP_PG_PASSWORD}
      - NLP_PG_CONTAINER_PORT=${NLP_PG_CONTAINER_PORT}
      - NLP_MONGO_HOSTNAME=${NLP_MONGO_HOSTNAME}
      - NLP_MONGO_CONTAINER_PORT=${NLP_MONGO_CONTAINER_PORT}
      - NLP_MONGO_DATABASE=${NLP_MONGO_DATABASE}
      - NLP_MONGO_WORKING_INDEX=${NLP_MONGO_WORKING_INDEX}
      - NLP_MONGO_WORKING_COLLECTION=${NLP_MONGO_WORKING_COLLECTION}
      - NLP_MONGO_USERNAME=${NLP_MONGO_USERNAME}
      - NLP_MONGO_PASSWORD=${NLP_MONGO_PASSWORD}
      - LUIGI_SCHEDULER_URL=${LUIGI_SCHEDULER_URL}
      - LUIGI_URL=${LUIGI_URL}
      - LUIGI_WORKERS=${LUIGI_WORKERS}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_HOST_PORT=${REDIS_HOST_PORT}
      - REDIS_CONTAINER_PORT=${REDIS_CONTAINER_PORT}
      - FHIR_CQL_EVAL_URL=${FHIR_CQL_EVAL_URL}
      - FHIR_DATA_SERVICE_URI=${FHIR_DATA_SERVICE_URI}
      - FHIR_TERMINOLOGY_SERVICE_URI=${FHIR_TERMINOLOGY_SERVICE_URI}
      - FHIR_TERMINOLOGY_SERVICE_ENDPOINT=${FHIR_TERMINOLOGY_SERVICE_ENDPOINT}
      - FHIR_TERMINOLOGY_USER_NAME=${FHIR_TERMINOLOGY_USER_NAME}
      - FHIR_TERMINOLOGY_USER_PASSWORD=${FHIR_TERMINOLOGY_USER_PASSWORD}
    networks:
      - cibmtr
    depends_on:
      - redis
      - nlp-solr
      - nlp-mongo
      - nlp-postgres
      - scheduler

  scheduler:
    container_name: LUIGI_SCHEDULER
    hostname: ${SCHEDULER_HOSTNAME}
    image: axiom/docker-luigi:2.7.1
    expose:
      - ${SCHEDULER_CONTAINER_PORT}
    environment:
      - LETSENCRYPT_HOST=${SCHEDULER_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_HOST=${SCHEDULER_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=${SCHEDULER_CONTAINER_PORT}
    networks:
      - cibmtr

  nlp-solr:
    container_name: NLP_SOLR
    hostname: ${NLP_SOLR_HOSTNAME}
    image: claritynlp/nlp-solr
    expose:
      - ${NLP_SOLR_CONTAINER_PORT}
    volumes:
      - nlp-solrdata:/opt/solr/server/solr/mycores
    environment:
      - SOLR_HEAP=${SOLR_HEAP}
      - LETSENCRYPT_HOST=${SOLR_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_HOST=${SOLR_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=${NLP_SOLR_CONTAINER_PORT}
    networks:
      - cibmtr

  nlp-mongo:
    container_name: NLP_MONGO
    hostname: ${NLP_MONGO_HOSTNAME}
    image: claritynlp/nlp-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=${NLP_MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${NLP_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${NLP_MONGO_PASSWORD}
    expose:
      - ${NLP_MONGO_CONTAINER_PORT}
    volumes:
      - nlp-mongodata:/data/db
    networks:
      - cibmtr

  nlp-postgres:
    container_name: NLP_POSTGRES
    hostname: ${NLP_PG_HOSTNAME}
    image: claritynlp/nlp-postgres
    command: postgres -c 'shared_buffers=512MB' -c 'max_connections=500'
    environment:
      POSTGRES_USER: ${NLP_PG_USER}
      POSTGRES_PASSWORD: ${NLP_PG_PASSWORD}
      POSTGRES_DB: ${NLP_PG_DATABASE}
      INIT_OMOP: ${INIT_OMOP}
    expose:
      - ${NLP_PG_CONTAINER_PORT}
    volumes:
      - nlp-pgdata:/var/lib/postgresql/data/
    networks:
      - cibmtr

  ingest-api:
    container_name: INGEST_API
    hostname: ${INGEST_API_HOSTNAME}
    image: claritynlp/ingest-api
    volumes:
      - /app/node_modules/ #empties container node_modules, forces bcrypt to be built on container
      - ingest-files:/var/lib/ingest-files
    expose:
      - ${INGEST_API_CONTAINER_PORT}
    entrypoint:
      - /app/wait-for-it-extra.sh
      - ${NLP_SOLR_HOSTNAME}:${NLP_SOLR_CONTAINER_PORT}
      - ${REDIS_HOSTNAME}:${REDIS_CONTAINER_PORT}
      - ${INGEST_MONGO_HOSTNAME}:${INGEST_MONGO_CONTAINER_PORT}
      - ${NLP_API_HOSTNAME}:${NLP_API_CONTAINER_PORT}
      - --timeout=420
      - --
      - pm2-runtime
    command: app.js
    environment:
      - NODE_ENV=production
      - JOB_TYPES=ingest
      - NLP_SOLR_HOSTNAME=${NLP_SOLR_HOSTNAME}
      - NLP_SOLR_CONTAINER_PORT=${NLP_SOLR_CONTAINER_PORT}
      - NLP_CORE_NAME=${NLP_CORE_NAME}
      - NLP_SOLR_URL_TOP_LEVEL=${NLP_SOLR_URL_TOP_LEVEL}
      - NLP_API_HOSTNAME=${NLP_API_HOSTNAME}
      - NLP_API_CONTAINER_PORT=${NLP_API_CONTAINER_PORT}
      - INTERVAL=${INTERVAL}
      - INGEST_MONGO_USERNAME=${INGEST_MONGO_USERNAME}
      - INGEST_MONGO_PASSWORD=${INGEST_MONGO_PASSWORD}
      - INGEST_MONGO_HOSTNAME=${INGEST_MONGO_HOSTNAME}
      - INGEST_MONGO_CONTAINER_PORT=${INGEST_MONGO_CONTAINER_PORT}
      - INGEST_MONGO_DATABASE=${INGEST_MONGO_DATABASE}
      - INGEST_CLIENT_HOST_PORT=${INGEST_CLIENT_HOST_PORT}
      - INGEST_API_LOG_LEVEL=${INGEST_API_LOG_LEVEL}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_CONTAINER_PORT=${REDIS_CONTAINER_PORT}
      - PROTOCOL=${PROTOCOL}
      - DOMAIN=${DOMAIN}
      - INGEST_CLIENT_SUBDOMAIN=${INGEST_CLIENT_SUBDOMAIN}
      - DASHBOARD_CLIENT_SUBDOMAIN=${DASHBOARD_CLIENT_SUBDOMAIN}
    networks:
      - cibmtr
    depends_on:
      - ingest-mongo
      - redis
      - nlp-solr
      - nlp-api

  ingest-mongo:
    container_name: ${INGEST_MONGO_CONTAINER_NAME}
    hostname: ${INGEST_MONGO_HOSTNAME}
    image: claritynlp/ingest-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=${INGEST_MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${INGEST_MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${INGEST_MONGO_PASSWORD}
    expose:
      - ${INGEST_MONGO_CONTAINER_PORT}
    volumes:
      - ingest-mongodata:/data/db
    networks:
      - cibmtr

  ingest-client:
    container_name: INGEST_CLIENT
    hostname: ${INGEST_CLIENT_HOSTNAME}
    image: claritynlp/ingest-client
    environment:
      - PORT=${INGEST_CLIENT_CONTAINER_PORT}
      - LETSENCRYPT_HOST=${INGEST_CLIENT_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_HOST=${INGEST_CLIENT_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=80
      - REACT_APP_IDENTITY_PROVIDER_URL=${IDENTITY_PROVIDER_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_API_HOST=${IDENTITY_AND_ACCESS_PROXY_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_DASHBOARD_URL=${DASHBOARD_CLIENT_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_RESULTS_URL=${RESULTS_CLIENT_SUBDOMAIN}.${DOMAIN}
    volumes:
      - /app/node_modules
    networks:
      - cibmtr

  redis:
    container_name: REDIS
    hostname: ${REDIS_HOSTNAME}
    image: redis:4.0.10
    expose:
      - ${REDIS_CONTAINER_PORT}
    volumes:
      - redisdata:/data
    networks:
      - cibmtr

  results-client:
    container_name: RESULTS_CLIENT
    hostname: ${RESULTS_CLIENT_HOSTNAME}
    image: claritynlp/results-client
    volumes:
      - /app/node_modules
    environment:
      - PORT=${RESULTS_CLIENT_CONTAINER_PORT}
      - LETSENCRYPT_HOST=${RESULTS_CLIENT_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_HOST=${RESULTS_CLIENT_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=80
      - REACT_APP_IDENTITY_PROVIDER_URL=${IDENTITY_PROVIDER_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_API_HOST=${IDENTITY_AND_ACCESS_PROXY_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_DASHBOARD_URL=${DASHBOARD_CLIENT_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_INGEST_URL=${INGEST_CLIENT_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_LUIGI_URL=${SCHEDULER_SUBDOMAIN}.${DOMAIN}
    networks:
      - cibmtr

  dashboard-client:
    container_name: DASHBOARD_CLIENT
    hostname: ${DASHBOARD_CLIENT_HOSTNAME}
    image: claritynlp/dashboard-client
    volumes:
      - /app/node_modules
    environment:
      - PORT=${DASHBOARD_CLIENT_CONTAINER_PORT}
      - LETSENCRYPT_HOST=${DASHBOARD_CLIENT_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_HOST=${DASHBOARD_CLIENT_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=80
      - REACT_APP_IDENTITY_PROVIDER_URL=${IDENTITY_PROVIDER_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_API_HOST=${IDENTITY_AND_ACCESS_PROXY_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_INGEST_URL=${INGEST_CLIENT_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_RESULTS_URL=${RESULTS_CLIENT_SUBDOMAIN}.${DOMAIN}
      - REACT_APP_DOCUMETATION_URL=https://claritynlp.readthedocs.io/en/latest/index.html
    networks:
      - cibmtr

  form:
    container_name: FORM
    hostname: form
    image: claritynlp/cibmtr-form
    volumes:
      - /app/node_modules
    environment:
      - PORT=${FORM_CONTAINER_PORT}
      - LETSENCRYPT_HOST=${FORM_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_HOST=${FORM_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=80
      - REACT_APP_CLARITY_NLPAAS_URL=https://${NLPAAS_SUBDOMAIN}.${DOMAIN}/job/${NLPAAS_CUSTOM_DIR}/4100r4/
      - REACT_APP_ISS=${FORM_ISS}
      - REACT_APP_SCOPES=${FORM_SCOPES}
      - REACT_APP_CLIENT_ID=${FORM_CLIENT_ID}
    networks:
      - cibmtr

  nlpaas:
    container_name: NLPAAS
    hostname: ${NLPAAS_HOSTNAME}
    image: claritynlp/clarity-paas
    expose:
      - ${NLPAAS_CONTAINER_PORT}
    entrypoint:
      - /api/wait-for-it-extra.sh
      - identity-provider:${IDENTITY_PROVIDER_CONTAINER_PORT}
      - --timeout=420
      - --extra=15
      - --
      - /api/load_nlpql.sh
    command: python3 app.py
    environment:
      - LETSENCRYPT_HOST=${NLPAAS_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_HOST=${NLPAAS_SUBDOMAIN}.${DOMAIN}
      - VIRTUAL_PORT=${NLPAAS_CONTAINER_PORT}
      - CUSTOM_S3_URL=${NLPAAS_CUSTOM_S3_URL}
      - CUSTOM_DIR=${NLPAAS_CUSTOM_DIR}
      - NLP_SOLR_URL=https://${IDENTITY_AND_ACCESS_PROXY_SUBDOMAIN}.${DOMAIN}/solr/sample
      - CLARITY_NLP_URL=https://${IDENTITY_AND_ACCESS_PROXY_SUBDOMAIN}.${DOMAIN}/nlp
      - CLARITY_TOKEN_URL=https://${IDENTITY_PROVIDER_SUBDOMAIN}.${DOMAIN}/connect/token
      - CLARITY_NLP_SECRET=${CLIENT_NLPASS_SECRET}
    networks:
      - cibmtr
    depends_on:
      - nlp-api

  cql-execution:
    container_name: CQL_EXECUTION
    hostname: cql-execution
    image: claritynlp/cqlexecutionservice:dstu2
    networks:
      - cibmtr
    depends_on:
      - nlp-api

  nginx-proxy:
    container_name: NGINX_PROXY
    hostname: nginx-proxy
    image: claritynlp/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - SOLR_USERNAME=${SOLR_USERNAME}
      - SOLR_PASSWORD=${SOLR_PASSWORD}
      - SOLR_SUBDOMAIN=${SOLR_SUBDOMAIN}
      - SCHEDULER_USERNAME=${SCHEDULER_USERNAME}
      - SCHEDULER_PASSWORD=${SCHEDULER_PASSWORD}
      - SCHEDULER_SUBDOMAIN=${SCHEDULER_SUBDOMAIN}
      - DOMAIN=${DOMAIN}
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - cibmtr

  letsencrypt:
    container_name: LETS_ENCRYPT
    hostname: nginx-proxy-le
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
    networks:
      - cibmtr
